import Head from 'next/head'
import Header from './Header/Header'

export default function Home() {
  return (
    <div>
      <Head>
        <title> Instagram with NextJs </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      hello
      {/* Header */}
      {/* Feed */}
      {/* Modal */}
      {/* <Header></Header> */}
      </div>
  )
}
